version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - revive
    - misspell
    - errcheck
    - ineffassign
    - gocritic
    - gosec
    - depguard

linters-settings:
  revive:
    severity: warning
    rules:
      - name: var-naming
        disabled: true
      - name: package-comments
        disabled: true
      - name: blank-imports
        disabled: true

  gosec:
    excludes:
      - G104
      - G304
      - G404

  depguard:
    rules:
      main:
        allow:
          - "*"
        deny:
          - pkg: github.com/pkg/errors
            desc: "use native Go errors"

issues:
  exclude-dirs:
    - internal/service/mocks

  exclude-rules:
    - linters:
        - stylecheck
      text: "ST1003"

  max-issues-per-linter: 50
  max-same-issues: 3
