// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/deimossy/pr-reviewer-assignment-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockPullRequestService is an autogenerated mock type for the PullRequestService type
type MockPullRequestService struct {
	mock.Mock
}

type MockPullRequestService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPullRequestService) EXPECT() *MockPullRequestService_Expecter {
	return &MockPullRequestService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, pr
func (_m *MockPullRequestService) Create(ctx context.Context, pr *models.PullRequest) error {
	ret := _m.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PullRequest) error); ok {
		r0 = rf(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPullRequestService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPullRequestService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - pr *models.PullRequest
func (_e *MockPullRequestService_Expecter) Create(ctx interface{}, pr interface{}) *MockPullRequestService_Create_Call {
	return &MockPullRequestService_Create_Call{Call: _e.mock.On("Create", ctx, pr)}
}

func (_c *MockPullRequestService_Create_Call) Run(run func(ctx context.Context, pr *models.PullRequest)) *MockPullRequestService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PullRequest))
	})
	return _c
}

func (_c *MockPullRequestService_Create_Call) Return(_a0 error) *MockPullRequestService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPullRequestService_Create_Call) RunAndReturn(run func(context.Context, *models.PullRequest) error) *MockPullRequestService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *MockPullRequestService) ListByUser(ctx context.Context, userID string) ([]models.PullRequestShort, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []models.PullRequestShort
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.PullRequestShort, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.PullRequestShort); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PullRequestShort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPullRequestService_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockPullRequestService_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPullRequestService_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockPullRequestService_ListByUser_Call {
	return &MockPullRequestService_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockPullRequestService_ListByUser_Call) Run(run func(ctx context.Context, userID string)) *MockPullRequestService_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPullRequestService_ListByUser_Call) Return(_a0 []models.PullRequestShort, _a1 error) *MockPullRequestService_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPullRequestService_ListByUser_Call) RunAndReturn(run func(context.Context, string) ([]models.PullRequestShort, error)) *MockPullRequestService_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function with given fields: ctx, prID
func (_m *MockPullRequestService) Merge(ctx context.Context, prID string) (*models.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPullRequestService_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type MockPullRequestService_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockPullRequestService_Expecter) Merge(ctx interface{}, prID interface{}) *MockPullRequestService_Merge_Call {
	return &MockPullRequestService_Merge_Call{Call: _e.mock.On("Merge", ctx, prID)}
}

func (_c *MockPullRequestService_Merge_Call) Run(run func(ctx context.Context, prID string)) *MockPullRequestService_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPullRequestService_Merge_Call) Return(_a0 *models.PullRequest, _a1 error) *MockPullRequestService_Merge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPullRequestService_Merge_Call) RunAndReturn(run func(context.Context, string) (*models.PullRequest, error)) *MockPullRequestService_Merge_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceReview provides a mock function with given fields: ctx, prID, oldReviewerID
func (_m *MockPullRequestService) ReplaceReview(ctx context.Context, prID string, oldReviewerID string) (string, *models.PullRequest, error) {
	ret := _m.Called(ctx, prID, oldReviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceReview")
	}

	var r0 string
	var r1 *models.PullRequest
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, *models.PullRequest, error)); ok {
		return rf(ctx, prID, oldReviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, prID, oldReviewerID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *models.PullRequest); ok {
		r1 = rf(ctx, prID, oldReviewerID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, prID, oldReviewerID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPullRequestService_ReplaceReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceReview'
type MockPullRequestService_ReplaceReview_Call struct {
	*mock.Call
}

// ReplaceReview is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - oldReviewerID string
func (_e *MockPullRequestService_Expecter) ReplaceReview(ctx interface{}, prID interface{}, oldReviewerID interface{}) *MockPullRequestService_ReplaceReview_Call {
	return &MockPullRequestService_ReplaceReview_Call{Call: _e.mock.On("ReplaceReview", ctx, prID, oldReviewerID)}
}

func (_c *MockPullRequestService_ReplaceReview_Call) Run(run func(ctx context.Context, prID string, oldReviewerID string)) *MockPullRequestService_ReplaceReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPullRequestService_ReplaceReview_Call) Return(_a0 string, _a1 *models.PullRequest, _a2 error) *MockPullRequestService_ReplaceReview_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPullRequestService_ReplaceReview_Call) RunAndReturn(run func(context.Context, string, string) (string, *models.PullRequest, error)) *MockPullRequestService_ReplaceReview_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPullRequestService creates a new instance of MockPullRequestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPullRequestService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPullRequestService {
	mock := &MockPullRequestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
