// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/deimossy/pr-reviewer-assignment-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockTeamService is an autogenerated mock type for the TeamService type
type MockTeamService struct {
	mock.Mock
}

type MockTeamService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamService) EXPECT() *MockTeamService_Expecter {
	return &MockTeamService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, team
func (_m *MockTeamService) Create(ctx context.Context, team *models.Team) error {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Team) error); ok {
		r0 = rf(ctx, team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTeamService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - team *models.Team
func (_e *MockTeamService_Expecter) Create(ctx interface{}, team interface{}) *MockTeamService_Create_Call {
	return &MockTeamService_Create_Call{Call: _e.mock.On("Create", ctx, team)}
}

func (_c *MockTeamService_Create_Call) Run(run func(ctx context.Context, team *models.Team)) *MockTeamService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Team))
	})
	return _c
}

func (_c *MockTeamService_Create_Call) Return(_a0 error) *MockTeamService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamService_Create_Call) RunAndReturn(run func(context.Context, *models.Team) error) *MockTeamService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockTeamService) GetByName(ctx context.Context, name string) (*models.Team, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Team, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Team); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockTeamService_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamService_Expecter) GetByName(ctx interface{}, name interface{}) *MockTeamService_GetByName_Call {
	return &MockTeamService_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockTeamService_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockTeamService_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamService_GetByName_Call) Return(_a0 *models.Team, _a1 error) *MockTeamService_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_GetByName_Call) RunAndReturn(run func(context.Context, string) (*models.Team, error)) *MockTeamService_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamService creates a new instance of MockTeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamService {
	mock := &MockTeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
